import { createHash } from 'node:crypto'
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { join, relative, resolve, sep } from 'node:path'

const dist = resolve(import.meta.dirname, '../dist')

async function listFiles(directory) {
  const entries = await readdir(directory, { withFileTypes: true })
  const files = await Promise.all(entries.map(async (entry) => {
    const path = join(directory, entry.name)
    return entry.isDirectory() ? listFiles(path) : [path]
  }))
  return files.flat()
}

const files = (await listFiles(dist))
  .filter((file) => relative(dist, file) !== 'sw.js')
  .sort()
const assets = files.map((file) => relative(dist, file).split(sep).join('/'))
if (!assets.includes('index.html')) throw new Error('The Web build has no index.html to cache')

const hash = createHash('sha256')
for (const file of files) {
  hash.update(relative(dist, file))
  hash.update(await readFile(file))
}
const revision = hash.digest('hex').slice(0, 16)

const source = `// Generated by scripts/generate-sw.mjs. Do not edit.
const CACHE_PREFIX = 'eotion-shell:' + new URL(self.registration.scope).pathname + ':'
const CACHE_NAME = CACHE_PREFIX + ${JSON.stringify(revision)}
const SHELL_FILES = ${JSON.stringify(assets)}
const SHELL_URLS = SHELL_FILES.map((file) => new URL(file, self.registration.scope).href)
const SHELL_PATHS = new Set(SHELL_URLS.map((url) => new URL(url).pathname))
const INDEX_URL = new URL('index.html', self.registration.scope).href

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.addAll(SHELL_URLS)))
})

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys()
    await Promise.all(names.filter((name) => name.startsWith(CACHE_PREFIX) && name !== CACHE_NAME)
      .map((name) => caches.delete(name)))
    await self.clients.claim()
  })())
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return
  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return
  const scopePath = new URL(self.registration.scope).pathname
  if (!url.pathname.startsWith(scopePath)) return
  const relativePath = url.pathname.slice(scopePath.length)
  if (relativePath === 'api' || relativePath.startsWith('api/')) return

  if (request.mode === 'navigate') {
    event.respondWith(fetch(request).catch(async () => {
      const cached = await caches.match(INDEX_URL)
      if (cached) return cached
      throw new Error('The Eotion app shell is unavailable offline')
    }))
    return
  }
  if (SHELL_PATHS.has(url.pathname)) {
    event.respondWith(caches.match(url.href, { ignoreSearch: true, ignoreVary: true }).then((cached) => cached || fetch(request)))
  }
})
`

await writeFile(join(dist, 'sw.js'), source, 'utf8')
