import {
  AlertTriangle,
  ArrowLeft,
  Bold,
  Bot,
  Check,
  ChevronDown,
  ChevronRight,
  Download,
  Eye,
  EyeOff,
  FileText,
  Heading,
  Image,
  Italic,
  List,
  LogOut,
  Menu,
  Moon,
  MoreHorizontal,
  Paperclip,
  Plus,
  Plug,
  Settings,
  Sun,
  Palette,
  UserRound,
  PanelsTopLeft,
  PanelLeftClose,
  PanelLeftOpen,
  RefreshCw,
  Search,
  Trash2,
  Type,
  Upload,
  X,
} from 'lucide'
import type { IconNode } from 'morphicons/vue'

export enum IconName {
  Menu = 'menu',
  SidebarClose = 'sidebar-close',
  SidebarOpen = 'sidebar-open',
  LogOut = 'log-out',
  X = 'x',
  Plus = 'plus',
  ChevronRight = 'chevron-right',
  ChevronDown = 'chevron-down',
  Check = 'check',
  More = 'more',
  FileText = 'file-text',
  Image = 'image',
  Paperclip = 'paperclip',
  Upload = 'upload',
  Download = 'download',
  Trash = 'trash',
  Refresh = 'refresh',
  Search = 'search',
  Alert = 'alert',
  ArrowLeft = 'arrow-left',
  Settings = 'settings',
  User = 'user',
  Appearance = 'appearance',
  Workspace = 'workspace',
  Mcp = 'mcp',
  Agent = 'agent',
  Sun = 'sun',
  Moon = 'moon',
  Eye = 'eye',
  EyeOff = 'eye-off',
  Heading = 'heading',
  List = 'list',
  Text = 'text',
  Bold = 'bold',
  Italic = 'italic',
}

export const iconNodes: Record<IconName, IconNode> = {
  [IconName.Menu]: Menu,
  [IconName.SidebarClose]: PanelLeftClose,
  [IconName.SidebarOpen]: PanelLeftOpen,
  [IconName.LogOut]: LogOut,
  [IconName.X]: X,
  [IconName.Plus]: Plus,
  [IconName.ChevronRight]: ChevronRight,
  [IconName.ChevronDown]: ChevronDown,
  [IconName.Check]: Check,
  [IconName.More]: MoreHorizontal,
  [IconName.FileText]: FileText,
  [IconName.Image]: Image,
  [IconName.Paperclip]: Paperclip,
  [IconName.Upload]: Upload,
  [IconName.Download]: Download,
  [IconName.Trash]: Trash2,
  [IconName.Refresh]: RefreshCw,
  [IconName.Search]: Search,
  [IconName.Alert]: AlertTriangle,
  [IconName.ArrowLeft]: ArrowLeft,
  [IconName.Settings]: Settings,
  [IconName.User]: UserRound,
  [IconName.Appearance]: Palette,
  [IconName.Workspace]: PanelsTopLeft,
  [IconName.Mcp]: Plug,
  [IconName.Agent]: Bot,
  [IconName.Sun]: Sun,
  [IconName.Moon]: Moon,
  [IconName.Eye]: Eye,
  [IconName.EyeOff]: EyeOff,
  [IconName.Heading]: Heading,
  [IconName.List]: List,
  [IconName.Text]: Type,
  [IconName.Bold]: Bold,
  [IconName.Italic]: Italic,
}
