import {
  AlertTriangle,
  ArrowLeft,
  ArrowUpDown,
  Bold,
  Bot,
  Check,
  ChevronDown,
  ChevronRight,
  Download,
  Database,
  Eye,
  EyeOff,
  FileText,
  Filter,
  FolderInput,
  GripVertical,
  Heading,
  Image,
  Info,
  Italic,
  Link,
  List,
  ListOrdered,
  ListTodo,
  LogOut,
  Menu,
  Moon,
  Minus,
  MoreHorizontal,
  Paperclip,
  Pencil,
  Plus,
  Plug,
  Quote,
  Code,
  Copy,
  Settings,
  Strikethrough,
  Sun,
  Table,
  Palette,
  UserRound,
  PanelsTopLeft,
  PanelLeftClose,
  PanelLeftOpen,
  RefreshCw,
  Search,
  Trash2,
  Type,
  Upload,
  X,
} from 'lucide'
import type { IconNode } from 'morphicons/vue'

export enum IconName {
  Menu = 'menu',
  SidebarClose = 'sidebar-close',
  SidebarOpen = 'sidebar-open',
  LogOut = 'log-out',
  X = 'x',
  Plus = 'plus',
  DragHandle = 'drag-handle',
  Database = 'database',
  ChevronRight = 'chevron-right',
  ChevronDown = 'chevron-down',
  Filter = 'filter',
  Sort = 'sort',
  Check = 'check',
  More = 'more',
  FileText = 'file-text',
  Rename = 'rename',
  Move = 'move',
  Image = 'image',
  Paperclip = 'paperclip',
  Upload = 'upload',
  Download = 'download',
  Trash = 'trash',
  Refresh = 'refresh',
  Search = 'search',
  Alert = 'alert',
  ArrowLeft = 'arrow-left',
  Settings = 'settings',
  User = 'user',
  Appearance = 'appearance',
  Workspace = 'workspace',
  Mcp = 'mcp',
  Agent = 'agent',
  Info = 'info',
  Sun = 'sun',
  Moon = 'moon',
  Eye = 'eye',
  EyeOff = 'eye-off',
  Heading = 'heading',
  List = 'list',
  ListOrdered = 'list-ordered',
  ListTodo = 'list-todo',
  Table = 'table',
  Quote = 'quote',
  Code = 'code',
  Copy = 'copy',
  Minus = 'minus',
  Text = 'text',
  Bold = 'bold',
  Italic = 'italic',
  Link = 'link',
  Strike = 'strike',
}

export const iconNodes: Record<IconName, IconNode> = {
  [IconName.Menu]: Menu,
  [IconName.SidebarClose]: PanelLeftClose,
  [IconName.SidebarOpen]: PanelLeftOpen,
  [IconName.LogOut]: LogOut,
  [IconName.X]: X,
  [IconName.Plus]: Plus,
  [IconName.DragHandle]: GripVertical,
  [IconName.Database]: Database,
  [IconName.ChevronRight]: ChevronRight,
  [IconName.ChevronDown]: ChevronDown,
  [IconName.Filter]: Filter,
  [IconName.Sort]: ArrowUpDown,
  [IconName.Check]: Check,
  [IconName.More]: MoreHorizontal,
  [IconName.FileText]: FileText,
  [IconName.Rename]: Pencil,
  [IconName.Move]: FolderInput,
  [IconName.Image]: Image,
  [IconName.Paperclip]: Paperclip,
  [IconName.Upload]: Upload,
  [IconName.Download]: Download,
  [IconName.Trash]: Trash2,
  [IconName.Refresh]: RefreshCw,
  [IconName.Search]: Search,
  [IconName.Alert]: AlertTriangle,
  [IconName.ArrowLeft]: ArrowLeft,
  [IconName.Settings]: Settings,
  [IconName.User]: UserRound,
  [IconName.Appearance]: Palette,
  [IconName.Workspace]: PanelsTopLeft,
  [IconName.Mcp]: Plug,
  [IconName.Agent]: Bot,
  [IconName.Info]: Info,
  [IconName.Sun]: Sun,
  [IconName.Moon]: Moon,
  [IconName.Eye]: Eye,
  [IconName.EyeOff]: EyeOff,
  [IconName.Heading]: Heading,
  [IconName.List]: List,
  [IconName.ListOrdered]: ListOrdered,
  [IconName.ListTodo]: ListTodo,
  [IconName.Table]: Table,
  [IconName.Quote]: Quote,
  [IconName.Code]: Code,
  [IconName.Copy]: Copy,
  [IconName.Minus]: Minus,
  [IconName.Text]: Type,
  [IconName.Bold]: Bold,
  [IconName.Italic]: Italic,
  [IconName.Link]: Link,
  [IconName.Strike]: Strikethrough,
}

/** Create a lightweight DOM icon for editor decorations outside Vue rendering. */
export function createIconElement(name: IconName, ownerDocument: Document = document): SVGSVGElement {
  const namespace = 'http://www.w3.org/2000/svg'
  const svg = ownerDocument.createElementNS(namespace, 'svg')
  svg.setAttribute('width', '18')
  svg.setAttribute('height', '18')
  svg.setAttribute('viewBox', '0 0 24 24')
  svg.setAttribute('fill', 'none')
  svg.setAttribute('stroke', 'currentColor')
  svg.setAttribute('stroke-width', '2')
  svg.setAttribute('stroke-linecap', 'round')
  svg.setAttribute('stroke-linejoin', 'round')
  svg.setAttribute('aria-hidden', 'true')
  for (const [tag, attributes] of iconNodes[name]) {
    const child = ownerDocument.createElementNS(namespace, tag)
    Object.entries(attributes).forEach(([attribute, value]) => child.setAttribute(attribute, String(value)))
    svg.append(child)
  }
  return svg
}
