import {
  AlertTriangle,
  Bold,
  Check,
  ChevronDown,
  ChevronRight,
  Download,
  FileText,
  Heading,
  Image,
  Italic,
  List,
  Menu,
  MoreHorizontal,
  Paperclip,
  Plus,
  RefreshCw,
  Search,
  Trash2,
  Type,
  Upload,
  X,
} from 'lucide'
import type { IconNode } from 'morphicons/vue'

export enum IconName {
  Menu = 'menu',
  X = 'x',
  Plus = 'plus',
  ChevronRight = 'chevron-right',
  ChevronDown = 'chevron-down',
  Check = 'check',
  More = 'more',
  FileText = 'file-text',
  Image = 'image',
  Paperclip = 'paperclip',
  Upload = 'upload',
  Download = 'download',
  Trash = 'trash',
  Refresh = 'refresh',
  Search = 'search',
  Alert = 'alert',
  Heading = 'heading',
  List = 'list',
  Text = 'text',
  Bold = 'bold',
  Italic = 'italic',
}

export const iconNodes: Record<IconName, IconNode> = {
  [IconName.Menu]: Menu,
  [IconName.X]: X,
  [IconName.Plus]: Plus,
  [IconName.ChevronRight]: ChevronRight,
  [IconName.ChevronDown]: ChevronDown,
  [IconName.Check]: Check,
  [IconName.More]: MoreHorizontal,
  [IconName.FileText]: FileText,
  [IconName.Image]: Image,
  [IconName.Paperclip]: Paperclip,
  [IconName.Upload]: Upload,
  [IconName.Download]: Download,
  [IconName.Trash]: Trash2,
  [IconName.Refresh]: RefreshCw,
  [IconName.Search]: Search,
  [IconName.Alert]: AlertTriangle,
  [IconName.Heading]: Heading,
  [IconName.List]: List,
  [IconName.Text]: Type,
  [IconName.Bold]: Bold,
  [IconName.Italic]: Italic,
}
